# Generated by Django 2.0.5 on 2021-02-21 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Img',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('date1', models.DateTimeField(auto_now=True, null=True)),
                ('date2', models.DateTimeField(auto_now_add=True, null=True)),
                ('img', models.ImageField(null=True, upload_to='img')),
            ],
        ),
    ]
